/*
 * Arith OpenAPI Specification
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// SumRequest struct for SumRequest
type SumRequest struct {
	A int32 `json:"a,omitempty"`
	B int32 `json:"b,omitempty"`
}
