/*
 * Arith OpenAPI Specification
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"fmt"
	"net/http"
	"strconv"
)

// 10_OMIT
// SumGet - Adds two numbers.
func SumGet(w http.ResponseWriter, r *http.Request) {
	// my implementation below
	r.ParseForm()
	a, err := strconv.Atoi(r.FormValue("num1"))
	if err != nil {
		http.Error(w, fmt.Sprintf("could not parse integer: %s", r.FormValue("num1")), 400)
		return
	}
	b, err := strconv.Atoi(r.FormValue("num2"))
	if err != nil {
		http.Error(w, fmt.Sprintf("could not parse integer: %s", r.FormValue("num2")), 400)
		return
	}
	// my implementation above
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
	fmt.Fprintf(w, `{"sum":%d}`, a+b) // my implementation
}

// 20_OMIT
