/*
 * Arith OpenAPI Specification
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type SumResponse struct {

	Sum int64 `json:"sum,omitempty"`
}
