openapi: "3.0.2"
info:
  title: Arith OpenAPI Specification
  version: "0.1"

servers:
- url: http://localhost:8080/

tags:
- name: Arithmetic
  description: Arithmetic is an arithmetic library.

paths:
  /sum:
    post:
      tags: ["Arithmetic"]
      summary: Adds two numbers.
      operationId: sum
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SumRequest'
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SumResponse'
components:
  schemas:
    SumRequest:
      type: object
      properties:
        a:
          type: integer
        b:
          type: integer
      example: {"a":2,"b":3}
    SumResponse:
      type: object
      properties:
        sum:
          type: integer
          format: int64
          example: 5