openapi: 3.0.2
info:
  title: Arith OpenAPI Specification
  version: "0.1"
servers:
- url: http://localhost:8080/
tags:
- description: Arithmetic is an arithmetic library.
  name: Arithmetic
paths:
  /sum:
    post:
      operationId: sum
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SumRequest'
        required: true
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SumResponse'
          description: successful operation
      summary: Adds two numbers.
      tags:
      - Arithmetic
components:
  schemas:
    SumRequest:
      example:
        a: 2
        b: 3
      properties:
        a:
          type: integer
        b:
          type: integer
      type: object
    SumResponse:
      example:
        sum: 5
      properties:
        sum:
          example: 5
          format: int64
          type: integer
      type: object
