openapi: "3.0.2"
info:
  title: Arith OpenAPI Specification
  version: "0.1"

servers:
- url: http://localhost:8080/

paths:
  /sum:
    get:
      tags: ["Arithmetic"]
      summary: Adds two numbers.
      parameters:
      - name: num1
        in: query
        required: true
        schema:
          $ref: '#/components/schemas/int64'
        example: 2
      - name: num2
        in: query
        required: true
        schema:
          $ref: '#/components/schemas/int64'
        example: 3
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SumResponse'
components:
  schemas:
    int64:
      type: integer
      format: int64
    SumResponse:
      type: object
      properties:
        sum:
          type: integer
          format: int64
          example: 5